insert into sr_option values (seq_sr_option.nextval, 'room', '냉장고');
insert into sr_option values (seq_sr_option.nextval, 'room', '세탁기');
insert into sr_option values (seq_sr_option.nextval, 'room', '책상');
insert into sr_option values (seq_sr_option.nextval, 'room', '침대');
insert into sr_option values (seq_sr_option.nextval, 'room', 'TV');
insert into sr_option values (seq_sr_option.nextval, 'room', '신발장');
insert into sr_option values (seq_sr_option.nextval, 'room', '에어컨');
insert into sr_option values (seq_sr_option.nextval, 'room', '전자도어락');
insert into sr_option values (seq_sr_option.nextval, 'room', '인덕션');
insert into sr_option values (seq_sr_option.nextval, 'room', '가스레인지');
insert into sr_option values (seq_sr_option.nextval, 'room', '옷장');
insert into sr_option values (seq_sr_option.nextval, 'room', '전자레인지');
insert into sr_option values (seq_sr_option.nextval, 'room', '비데');
insert into sr_option values (seq_sr_option.nextval, 'room', '정수기');
insert into sr_option values (seq_sr_option.nextval, 'etc', '반려동물가능');
insert into sr_option values (seq_sr_option.nextval, 'etc', '주차가능');
insert into sr_option values (seq_sr_option.nextval, 'etc', 'CCTV');
insert into sr_option values (seq_sr_option.nextval, 'etc', '화재경보기');

insert into sr_tag values (seq_sr_tag.nextval, '3','고양이');
insert into sr_tag values (seq_sr_tag.nextval, '3','반려동물');
insert into sr_tag values (seq_sr_tag.nextval, '5','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '5','치안');
insert into sr_tag values (seq_sr_tag.nextval, '5','안심귀가');
insert into sr_tag values (seq_sr_tag.nextval, '8','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '8','단기가능');
insert into sr_tag values (seq_sr_tag.nextval, '10','여성전용');
insert into sr_tag values (seq_sr_tag.nextval, '10','안심귀가');
insert into sr_tag values (seq_sr_tag.nextval, '11','저렴한방');
insert into sr_tag values (seq_sr_tag.nextval, '12','예쁜방');
insert into sr_tag values (seq_sr_tag.nextval, '12','깨끗');
insert into sr_tag values (seq_sr_tag.nextval, '13','예쁜방');
insert into sr_tag values (seq_sr_tag.nextval, '13','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '14','옥탑방');
insert into sr_tag values (seq_sr_tag.nextval, '14','루프탑');
insert into sr_tag values (seq_sr_tag.nextval, '14','뷰맛집');
insert into sr_tag values (seq_sr_tag.nextval, '16','단기가능');
insert into sr_tag values (seq_sr_tag.nextval, '16','개인실');
insert into sr_tag values (seq_sr_tag.nextval, '17','고시원');
insert into sr_tag values (seq_sr_tag.nextval, '17','개인실');
insert into sr_tag values (seq_sr_tag.nextval, '17','단기가능');
insert into sr_tag values (seq_sr_tag.nextval, '18','가성비');
insert into sr_tag values (seq_sr_tag.nextval, '18','저렴');
insert into sr_tag values (seq_sr_tag.nextval, '18','보증금없음');
insert into sr_tag values (seq_sr_tag.nextval, '20','테라스');
insert into sr_tag values (seq_sr_tag.nextval, '20','뷰맛집');
insert into sr_tag values (seq_sr_tag.nextval, '22','오피스텔');
insert into sr_tag values (seq_sr_tag.nextval, '22','보안');
insert into sr_tag values (seq_sr_tag.nextval, '22','치안');
insert into sr_tag values (seq_sr_tag.nextval, '23','보증금없음');
insert into sr_tag values (seq_sr_tag.nextval, '25','단기가능');
insert into sr_tag values (seq_sr_tag.nextval, '25','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '28','단기가능');
insert into sr_tag values (seq_sr_tag.nextval, '29','남성전용');
insert into sr_tag values (seq_sr_tag.nextval, '29','저렴한방');
insert into sr_tag values (seq_sr_tag.nextval, '31','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '33','개인실');
insert into sr_tag values (seq_sr_tag.nextval, '33','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '35','여성전용');
insert into sr_tag values (seq_sr_tag.nextval, '35','치안');
insert into sr_tag values (seq_sr_tag.nextval, '35','안심귀가');
insert into sr_tag values (seq_sr_tag.nextval, '36','보증금조절가능');
insert into sr_tag values (seq_sr_tag.nextval, '36','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '38','보증금없음');
insert into sr_tag values (seq_sr_tag.nextval, '39','남성전용');
insert into sr_tag values (seq_sr_tag.nextval, '39','이사지원금');
insert into sr_tag values (seq_sr_tag.nextval, '41','사생활');
insert into sr_tag values (seq_sr_tag.nextval, '41','개인실');
insert into sr_tag values (seq_sr_tag.nextval, '41','단기가능');
insert into sr_tag values (seq_sr_tag.nextval, '42','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '42','단기가능');
insert into sr_tag values (seq_sr_tag.nextval, '43','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '43','주차가능');
insert into sr_tag values (seq_sr_tag.nextval, '44','아파트');
insert into sr_tag values (seq_sr_tag.nextval, '44','사생활');
insert into sr_tag values (seq_sr_tag.nextval, '47','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '47','깔끔');
insert into sr_tag values (seq_sr_tag.nextval, '48','안심귀가');
insert into sr_tag values (seq_sr_tag.nextval, '48','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '49','단기가능');
insert into sr_tag values (seq_sr_tag.nextval, '49','보증금조절가능');
insert into sr_tag values (seq_sr_tag.nextval, '51','이태원클라쓰');
insert into sr_tag values (seq_sr_tag.nextval, '51','뷰맛집');
insert into sr_tag values (seq_sr_tag.nextval, '51','루프탑');
insert into sr_tag values (seq_sr_tag.nextval, '52','샤로수길');
insert into sr_tag values (seq_sr_tag.nextval, '52','역세권');
insert into sr_tag values (seq_sr_tag.nextval, '53','예쁜인테리어');
insert into sr_tag values (seq_sr_tag.nextval, '53','외국인가능');
insert into sr_tag values (seq_sr_tag.nextval, '54','역세권');
insert into sr_tag values (seq_sr_tag.nextval, '54','샤로수길');
insert into sr_tag values (seq_sr_tag.nextval, '55','루프탑');
insert into sr_tag values (seq_sr_tag.nextval, '55','주차가능');
insert into sr_tag values (seq_sr_tag.nextval, '56','깔끔');
insert into sr_tag values (seq_sr_tag.nextval, '56','안심귀가');
insert into sr_tag values (seq_sr_tag.nextval, '57','깔끔');
insert into sr_tag values (seq_sr_tag.nextval, '57','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '58','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '58','역세권');
insert into sr_tag values (seq_sr_tag.nextval, '59','단기');
insert into sr_tag values (seq_sr_tag.nextval, '59','외국인가능');
insert into sr_tag values (seq_sr_tag.nextval, '60','루프탑');
insert into sr_tag values (seq_sr_tag.nextval, '60','감성인테리어');
insert into sr_tag values (seq_sr_tag.nextval, '61','역세권');
insert into sr_tag values (seq_sr_tag.nextval, '61','한강공원');
insert into sr_tag values (seq_sr_tag.nextval, '62','강남');
insert into sr_tag values (seq_sr_tag.nextval, '62','역세권');
insert into sr_tag values (seq_sr_tag.nextval, '63','가로수길');
insert into sr_tag values (seq_sr_tag.nextval, '63','단기');
insert into sr_tag values (seq_sr_tag.nextval, '64','강남');
insert into sr_tag values (seq_sr_tag.nextval, '64','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '65','보증금없음');
insert into sr_tag values (seq_sr_tag.nextval, '65','역세권');
insert into sr_tag values (seq_sr_tag.nextval, '66','보증금없음');
insert into sr_tag values (seq_sr_tag.nextval, '66','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '67','보증금없음');
insert into sr_tag values (seq_sr_tag.nextval, '67','역세권');
insert into sr_tag values (seq_sr_tag.nextval, '68','보증금없음');
insert into sr_tag values (seq_sr_tag.nextval, '68','역세권');
insert into sr_tag values (seq_sr_tag.nextval, '69','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '69','역세권');
insert into sr_tag values (seq_sr_tag.nextval, '70','보증금없음');
insert into sr_tag values (seq_sr_tag.nextval, '70','역세권');
insert into sr_tag values (seq_sr_tag.nextval, '71','오피스텔');
insert into sr_tag values (seq_sr_tag.nextval, '71','강남');
insert into sr_tag values (seq_sr_tag.nextval, '71','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '71','깔끔');
insert into sr_tag values (seq_sr_tag.nextval, '72','오피스텔');
insert into sr_tag values (seq_sr_tag.nextval, '72','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '72','보안');
insert into sr_tag values (seq_sr_tag.nextval, '72','안전');
insert into sr_tag values (seq_sr_tag.nextval, '73','사생활');
insert into sr_tag values (seq_sr_tag.nextval, '73','비흡연');
insert into sr_tag values (seq_sr_tag.nextval, '73','여성전용');
insert into sr_tag values (seq_sr_tag.nextval, '73','치안');
insert into sr_tag values (seq_sr_tag.nextval, '74','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '74','투룸');
insert into sr_tag values (seq_sr_tag.nextval, '74','즉시입주');
insert into sr_tag values (seq_sr_tag.nextval, '74','서울대');
insert into sr_tag values (seq_sr_tag.nextval, '75','강아지');
insert into sr_tag values (seq_sr_tag.nextval, '75','반려견');
insert into sr_tag values (seq_sr_tag.nextval, '75','투룸');
insert into sr_tag values (seq_sr_tag.nextval, '76','사생활');
insert into sr_tag values (seq_sr_tag.nextval, '76','석촌호수');
insert into sr_tag values (seq_sr_tag.nextval, '76','송리단길');
insert into sr_tag values (seq_sr_tag.nextval, '77','보증금없음');
insert into sr_tag values (seq_sr_tag.nextval, '77','반려동물');
insert into sr_tag values (seq_sr_tag.nextval, '77','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '78','깔끔');
insert into sr_tag values (seq_sr_tag.nextval, '78','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '78','큰방');
insert into sr_tag values (seq_sr_tag.nextval, '79','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '79','역세권');
insert into sr_tag values (seq_sr_tag.nextval, '79','저렴');
insert into sr_tag values (seq_sr_tag.nextval, '80','보증금없음');
insert into sr_tag values (seq_sr_tag.nextval, '80','착한월세');
insert into sr_tag values (seq_sr_tag.nextval, '80','신축');
insert into sr_tag values (seq_sr_tag.nextval, '81','보증금없음');
insert into sr_tag values (seq_sr_tag.nextval, '81','역세권');
insert into sr_tag values (seq_sr_tag.nextval, '82','투룸');
insert into sr_tag values (seq_sr_tag.nextval, '82','거실');
insert into sr_tag values (seq_sr_tag.nextval, '82','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '83','쓰리룸');
insert into sr_tag values (seq_sr_tag.nextval, '83','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '83','역세권');
insert into sr_tag values (seq_sr_tag.nextval, '83','성별무관');
insert into sr_tag values (seq_sr_tag.nextval, '84','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '84','매너');
insert into sr_tag values (seq_sr_tag.nextval, '85','보증금없음');
insert into sr_tag values (seq_sr_tag.nextval, '86','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '86','조용');
insert into sr_tag values (seq_sr_tag.nextval, '86','사생활');
insert into sr_tag values (seq_sr_tag.nextval, '87','성별무관');
insert into sr_tag values (seq_sr_tag.nextval, '87','반려동물');
insert into sr_tag values (seq_sr_tag.nextval, '87','운동');
insert into sr_tag values (seq_sr_tag.nextval, '88','성별무관');
insert into sr_tag values (seq_sr_tag.nextval, '88','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '89','쓰리룸');
insert into sr_tag values (seq_sr_tag.nextval, '89','깔끔');
insert into sr_tag values (seq_sr_tag.nextval, '89','성별무관');
insert into sr_tag values (seq_sr_tag.nextval, '90','보증금없음');
insert into sr_tag values (seq_sr_tag.nextval, '90','주차가능');
insert into sr_tag values (seq_sr_tag.nextval, '90','비흡연');
insert into sr_tag values (seq_sr_tag.nextval, '91','큰방');
insert into sr_tag values (seq_sr_tag.nextval, '91','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '91','성별무관');
insert into sr_tag values (seq_sr_tag.nextval, '91','역세권');
insert into sr_tag values (seq_sr_tag.nextval, '92','고양이');
insert into sr_tag values (seq_sr_tag.nextval, '92','역세권');
insert into sr_tag values (seq_sr_tag.nextval, '93','주차가능');
insert into sr_tag values (seq_sr_tag.nextval, '93','큰방');
insert into sr_tag values (seq_sr_tag.nextval, '93','테라스');
insert into sr_tag values (seq_sr_tag.nextval, '93','뷰맛집');
insert into sr_tag values (seq_sr_tag.nextval, '93','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '94','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '94','뷰맛집');
insert into sr_tag values (seq_sr_tag.nextval, '94','안심귀가');
insert into sr_tag values (seq_sr_tag.nextval, '95','반려동물');
insert into sr_tag values (seq_sr_tag.nextval, '95','오피스텔');
insert into sr_tag values (seq_sr_tag.nextval, '95','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '96','역세권');
insert into sr_tag values (seq_sr_tag.nextval, '96','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '97','쾌적');
insert into sr_tag values (seq_sr_tag.nextval, '97','역세권');
insert into sr_tag values (seq_sr_tag.nextval, '98','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '98','주차가능');
insert into sr_tag values (seq_sr_tag.nextval, '99','역세권');
insert into sr_tag values (seq_sr_tag.nextval, '99','성별무관');
insert into sr_tag values (seq_sr_tag.nextval, '100','풀옵션');
insert into sr_tag values (seq_sr_tag.nextval, '100','샤로수길');
insert into sr_tag values (seq_sr_tag.nextval, '100','서울대');

insert into sr_room_option values(seq_sr_room_option.nextval, 1,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 1,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 1,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 1,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 1,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 2,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 2,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 2,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 2,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 2,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 3,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 3,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 3,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 3,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 3,16);
insert into sr_room_option values(seq_sr_room_option.nextval, 3,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 4,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 4,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 4,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 4,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 4,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 5,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 5,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 5,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 5,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 5,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 6,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 6,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 6,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 6,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 6,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 7,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 7,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 7,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 7,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 7,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 8,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 8,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 8,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 8,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 8,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 9,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 9,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 9,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 9,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 9,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 10,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 10,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 10,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 10,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 10,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 11,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 11,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 11,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 11,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 11,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 12,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 12,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 12,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 12,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 12,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 13,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 13,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 13,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 13,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 13,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 14,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 14,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 14,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 14,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 14,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 15,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 15,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 15,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 15,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 15,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 16,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 16,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 16,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 16,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 16,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 17,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 17,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 17,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 17,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 17,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 18,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 18,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 18,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 18,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 18,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 19,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 19,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 19,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 19,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 19,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 20,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 20,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 20,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 20,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 20,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 21,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 22,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 23,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 24,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 25,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 22,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 22,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 22,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 22,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 22,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 23,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 23,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 23,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 23,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 23,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 24,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 24,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 24,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 24,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 24,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 25,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 25,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 25,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 25,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 25,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 26,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 26,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 26,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 26,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 26,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 27,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 27,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 27,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 27,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 27,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 28,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 28,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 28,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 28,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 28,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 29,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 29,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 29,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 29,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 29,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 30,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 30,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 30,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 30,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 30,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 31,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 31,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 31,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 31,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 31,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 32,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 32,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 32,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 32,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 32,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 33,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 33,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 33,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 33,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 33,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 34,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 34,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 34,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 34,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 34,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 35,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 35,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 35,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 35,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 35,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 36,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 36,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 36,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 36,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 36,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 37,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 37,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 37,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 37,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 37,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 38,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 38,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 38,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 38,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 38,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 39,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 39,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 39,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 39,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 39,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 40,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 40,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 40,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 40,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 40,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 41,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 41,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 41,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 41,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 41,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 42,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 42,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 42,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 42,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 42,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 43,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 43,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 43,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 43,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 43,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 44,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 44,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 44,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 44,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 44,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 45,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 45,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 45,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 45,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 45,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 46,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 46,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 46,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 46,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 46,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 47,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 47,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 47,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 47,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 47,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 48,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 48,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 48,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 48,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 48,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 49,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 49,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 49,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 49,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 49,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 50,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 50,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 50,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 50,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 50,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 51,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 51,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 51,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 51,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 51,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 52,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 52,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 52,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 52,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 52,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 53,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 53,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 53,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 53,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 53,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 54,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 54,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 54,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 54,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 54,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 55,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 55,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 55,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 55,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 55,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 56,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 56,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 56,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 56,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 56,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 57,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 57,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 57,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 57,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 57,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 58,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 58,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 58,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 58,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 58,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 59,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 59,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 59,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 59,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 59,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 60,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 60,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 60,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 60,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 60,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 61,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 61,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 61,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 61,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 61,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 62,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 62,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 62,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 62,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 62,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 63,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 63,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 63,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 63,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 63,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 64,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 64,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 64,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 64,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 64,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 65,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 65,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 65,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 65,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 65,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 66,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 66,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 66,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 66,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 66,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 67,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 67,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 67,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 67,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 67,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 68,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 68,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 68,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 68,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 68,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 69,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 69,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 69,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 69,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 69,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 70,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 70,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 70,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 70,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 70,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 71,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 71,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 71,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 71,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 71,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 72,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 72,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 72,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 72,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 72,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 73,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 73,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 73,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 73,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 73,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 74,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 74,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 74,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 74,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 74,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 75,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 75,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 75,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 75,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 75,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 76,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 76,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 76,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 76,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 76,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 77,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 77,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 77,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 77,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 77,16);
insert into sr_room_option values(seq_sr_room_option.nextval, 77,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 78,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 78,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 78,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 78,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 78,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 79,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 79,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 79,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 79,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 79,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 80,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 80,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 80,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 80,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 80,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 81,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 81,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 81,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 81,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 81,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 82,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 82,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 82,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 82,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 82,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 83,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 83,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 83,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 83,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 83,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 84,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 84,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 84,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 84,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 84,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 85,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 85,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 85,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 85,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 85,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 86,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 86,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 86,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 86,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 86,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 87,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 87,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 87,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 87,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 87,16);
insert into sr_room_option values(seq_sr_room_option.nextval, 87,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 88,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 88,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 88,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 88,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 88,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 89,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 89,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 89,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 89,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 89,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 90,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 90,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 90,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 90,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 90,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 91,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 91,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 91,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 91,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 91,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 92,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 92,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 92,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 92,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 92,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 93,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 93,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 93,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 93,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 93,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 94,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 94,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 94,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 94,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 94,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 95,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 95,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 95,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 95,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 95,16);
insert into sr_room_option values(seq_sr_room_option.nextval, 95,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 96,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 96,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 96,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 96,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 96,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 97,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 97,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 97,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 97,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 97,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 98,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 98,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 98,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 98,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 98,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 99,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 99,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 99,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 99,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 99,10);
insert into sr_room_option values(seq_sr_room_option.nextval, 100,1);
insert into sr_room_option values(seq_sr_room_option.nextval, 100,2);
insert into sr_room_option values(seq_sr_room_option.nextval, 100,7);
insert into sr_room_option values(seq_sr_room_option.nextval, 100,8);
insert into sr_room_option values(seq_sr_room_option.nextval, 100,10);
